---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Packages required for support
support_util_packages:
  - bash-completion
  - bridge-utils
  - dstat
  - htop
  - iotop
  - iptables-persistent
  - lsof
  - openssh-server
  - sudo
  - tcpdump
  - vim

support_host_packages:
  - linux-crashdump
  - debootstrap
  - lvm2
  - ntp
  - ntpdate
  - vlan

support_neutron_debug_packages:
  - arping
  - ethtool

# kernel modules required on hosts
rpc_host_kernel_modules:
  - bonding
  - 8021q

# sysctl parameters required on hosts
rpc_host_kernel_sysctl:
  - { key: 'net.ipv4.ip_forward', value: 1 }
  - { key: 'net.ipv4.conf.all.rp_filter', value: 0 }
  - { key: 'net.ipv4.conf.default.rp_filter', value: 0 }

holland_repo_package_name: holland
holland_service_name: holland

holland_repo_path: "holland_{{ holland_git_install_branch | replace('/', '_') }}"

holland_git_repo: https://github.com/holland-backup/holland
holland_git_install_branch: "v1.0.10"
holland_git_dest: "/opt/{{ holland_repo_path }}"
# git_repo_plugins are other installable packages contained within the same git repo
holland_git_repo_plugins:
  - { path: "plugins", package: "holland.lib.common" }
  - { path: "plugins", package: "holland.lib.mysql" }
  - { path: "plugins", package: "holland.backup.xtrabackup" }

holland_pip_wheel_name: holland

holland_packages:
  - git

holland_venv_enabled: True
holland_venv_bin: "/openstack/venvs/holland-{{ rpc_release }}/bin"
holland_venv: "/openstack/venvs/holland-{{ rpc_release }}"

holland_pip_dependencies:
  - MySQL-python

hwraid_apt_repo_url: "http://mirror.rackspace.com/hwraid.le-vert.net/ubuntu/"

hwraid_apt_keys:
  - { url: "http://mirror.rackspace.com/hwraid.le-vert.net/ubuntu/hwraid.le-vert.net.gpg.key", state: "present" }

hwraid_apt_packages:
  - megacli
  - lsiutil

holland_requires_dependencies:
  - virtualenv
  - virtualenv-tools

magnum_kubectl_version: 'v1.5.3'
magnum_kubectl_url: 'https://storage.googleapis.com/kubernetes-release/release/{{ magnum_kubectl_version }}/bin/linux/amd64/kubectl'
magnum_carina_version: 'v2.1.3'
magnum_carina_url: 'https://download.getcarina.com/carina/{{ magnum_carina_version }}/Linux/x86_64/carina'

sos_git_repo: https://github.com/sosreport/sos.git
sos_git_install_branch: 4e7ecf0f2ffb6789247b4b742b154508f83bdc72
sos_git_dest: /opt/sos
sos_packages:
  - gettext
sos_pip_dependencies:
  - six
