---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Packages required for support
support_util_packages:
  - bash-completion
  - bridge-utils
  - dstat
  - htop
  - iotop
  - iptables-persistent
  - lsof
  - openssh-server
  - sudo
  - tcpdump
  - vim

support_host_packages:
  - linux-crashdump
  - debootstrap
  - lvm2
  - ntp
  - ntpdate
  - vlan

support_neutron_debug_packages:
  - arping
  - ethtool

# kernel modules required on hosts
rpc_host_kernel_modules:
  - bonding
  - 8021q

# sysctl parameters required on hosts
rpc_host_kernel_sysctl:
  - { key: 'net.ipv4.ip_forward', value: 1 }
  - { key: 'net.ipv4.conf.all.rp_filter', value: 0 }
  - { key: 'net.ipv4.conf.default.rp_filter', value: 0 }

holland_repo_package_name: holland
holland_service_name: holland

holland_repo_path: "holland_{{ holland_git_install_branch | replace('/', '_') }}"

holland_git_repo: https://github.com/holland-backup/holland
holland_git_install_branch: "v1.0.10"
holland_git_dest: "/opt/{{ holland_repo_path }}"
# git_repo_plugins are other installable packages contained within the same git repo
holland_git_repo_plugins:
  - { path: "plugins", package: "holland.lib.common" }
  - { path: "plugins", package: "holland.lib.mysql" }
  - { path: "plugins", package: "holland.backup.xtrabackup" }

holland_pip_wheel_name: holland

holland_packages:
  - mariadb-client
  - xtrabackup

holland_venv_enabled: False
holland_venv_tag: untagged
holland_venv_bin: "/openstack/venvs/holland-{{ holland_venv_tag }}/bin"
holland_non_venv_bin: '/usr/local/bin'
pccommon_venv_enabled: False
pccommon_venv_tag: untagged
pccommon_venv_bin: "/openstack/venvs/pccommon-{{ pccommon_venv_tag }}/bin"
pccommon_non_venv_bin: '/usr/local/bin'

holland_pip_dependencies:
  - MySQL-python

hwraid_apt_repo_url: "http://hwraid.le-vert.net/ubuntu"

hwraid_apt_repos:
  - { repo: "deb {{ hwraid_apt_repo_url }} {{ ansible_lsb.codename }} main", state: "present" }

hwraid_apt_keys:
  - { url: "http://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key", state: "present" }

hwraid_apt_packages:
  - megacli
  - lsiutil
