language: python

before_script:
- pip install 'tox<2.4.0,>=2.0'

script: tox

notifications:
    email: false

matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=ansible-lint
    - python: 2.7
      env: TOXENV=releasenotes
    - python: 2.7
      env: TOXENV=bashate

sudo: false