language: python

before_script:
- pip install -U tox pip
# NOTE(sigmavirus24): pycparser 2.14's wheel on PyPI is broken. Using
# --no-binary below ignores the wheel, downloads the source distribution and
# avoids the issue when installing cryptography for ansible.
# This is a temporary workaround and should be removed in due time.
- pip2 install --no-binary ':all:' pycparser
- pip2 install --force-reinstall 'ansible===1.9.4'
- ansible-galaxy install --role-file=ansible-role-requirements.yml --force --roles-path=/home/travis/build/rcbops/rpc-openstack/rpcd/playbooks/roles

script: tox

notifications:
    email: false

matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=ansible-lint

sudo: false
