---
- name: Dynamic inclusion of container
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - container-vars.yml
  vars:
    image_name: "{{ lookup('env', 'CONTAINER_TYPE') | default('keystone', True) }}"
  tasks:
    - name: prepare group for integrity checking
      add_host:
        name: "/tmp/{{ image_name }}/rootfs/"
        groups: "lxc_container_artifact"
        container_name: "LXC_NAME"
        physical_host: "localhost"

- name: Check integrity
  hosts: lxc_container_artifact
  connection: chroot
  gather_facts: no
  vars_files:
    - container-vars.yml
  vars:
    image_name: "{{ lookup('env', 'CONTAINER_TYPE') | default('keystone', True) }}"
    base_url: "http://rpc-repo.rackspace.com"
    arch: "x86_64"
    container_artifact_url: "{{ base_url }}/venvs/{{ rpc_release }}/ubuntu/{{ image_name }}-{{ rpc_release}}-{{ arch }}.tgz"
  tasks:
    - name: Fetch get-pip for comparison
      get_url:
        url: "{{ base_url }}/os-releases/{{ rpc_release }}/get-pip.py"
        dest: /opt/get-pip.py
        force: yes #Ensure it's redownloaded for testing purposes, not directly ok.
    - name: Check apt source is pointing to rax mirror
      find:
        paths: /etc/apt/sources.list.d
        contains:
          - ".*{{ base_url }}.*{{ rpc_release }}.*"
      register: matching_files
    - debug:
        var: matching_files
    # TODO(evrardjp): Refactor this to avoid being on the same codepath as the building.
    - name: Fetch venv from pre-build venv artifact for comparison
      get_url:
        url: "{{ container_artifact_url }}"
        dest: "{{ /var/cache/{{ container_artifact_url | basename }}"
        force: yes #Ensure it's redownloaded
        checksum: "sha1:{{ lookup('url', container_artifact_url  | replace('tgz', 'checksum')) }}"
