---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Nova config overrides
# NOTE: Due to a bug with nova, this variable cannot be set to true
# if the environment needs to be able to boot an instance from
# a volume
# https://bugs.launchpad.net/nova/+bug/1648324
#nova_cross_az_attach: False
nova_console_type: novnc

# Memcached overrides
# https://github.com/rcbops/rpc-openstack/issues/1048
# memcached_memory is calculated via https://github.com/openstack/openstack-ansible-memcached_server/blob/master/defaults/main.yml#L33
# based on container memory but this determination it not necessarily correct,
# since memory utilization is primarily driven by the objects placed in memcached.
memcached_connections: 16384

# Galera overrides
galera_cluster_name: rpc_galera_cluster

## Enable Neutron l2_population
# We are overriding the default value for neutron_l2_population. Please see
# https://github.com/rcbops/rpc-openstack/issues/973 for further details.
neutron_l2_population: True

# Based on https://github.com/rcbops/rpc-openstack/issues/1149
# L3HA has to be disabled until all major issues are fixed.
neutron_neutron_conf_overrides:
  DEFAULT:
    l3_ha: False

#Set the default for Neutron-HA-tool to true
neutron_legacy_ha_tool_enabled: true

repo_build_upper_constraints_overrides:
  # Due to https://bugs.launchpad.net/ceilometer/+bug/1660800, gnocchiclient
  # must be pinned to < 3.0.0. This constraint matches what is defined in
  # the optional dependencies specfied here:
  # https://github.com/openstack/ceilometer/blob/stable/newton/setup.cfg#L36
  - "gnocchiclient>=2.2.0,<3.0.0"

# Increase interval between checks after container start.
# Reduces the "Wait for container ssh" error.
ssh_delay: 60

# Use the correct secrets file
osa_secrets_file_name: "user_osa_secrets.yml"

# Disable glance image cache
glance_flavor: keystone
glance_glance_api_conf_overrides:
  DEFAULT:
    image_cache_dir: None

# Adding elastic search and kibana to haproxy_extra_services
haproxy_extra_services:
  - service:
      haproxy_service_name: elasticsearch
      haproxy_backend_nodes: "{{ groups['elasticsearch'] | default([]) }}"
      haproxy_ssl: False
      haproxy_port: 9200
      haproxy_balance_type: http
      haproxy_backend_options:
        - "httpchk /healthcheck"
  - service:
      haproxy_service_name: kibana_ssl
      haproxy_backend_nodes: "{{ groups['kibana'] | default([]) }}"
      haproxy_ssl: False
      haproxy_port: 8443
      haproxy_balance_type: tcp
      haproxy_backend_options:
        - "ssl-hello-chk"

# RI-357 Tempest Overrides
# TODO(d34dh0r53): Once the test_minimum_basic_scenario is working we can remove
# this
tempest_test_blacklist:
  - tempest.scenario.test_minimum_basic
