---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The directory we want to apply patches to.
patcher_dest_dir: "/opt/rpc-openstack/openstack-ansible"

# The directory we want to apply patches from
patcher_src_dir: "/opt/rpc-openstack/rpcd/patches"

# The files we want to apply
# This is a list of files in patcher_src_dir, and will be applied
# in the order that they are defined in the list.
# patcher_files:
