---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Restart rackspace-monitoring-agent service
  service:
    name: rackspace-monitoring-agent
    state: restarted
  tags:
    - maas-setup
    - rackspace-monitoring-agent-setup
    - rackspace-monitoring-agent-restart

# https://github.com/rcbops/u-suk-dev/issues/481
# For Liberty to Mitaka upgrades the checks are not getting properly registered.
# Restarting the agent seems to clear out the problematic checks.
- name: Wait for checks to register
  pause:
    minutes: 1
  tags:
    - maas-setup
    - rackspace-monitoring-agent-setup
    - rackspace-monitoring-agent-restart

- name: Restart rackspace-monitoring-agent service a second time
  service:
    name: rackspace-monitoring-agent
    state: restarted
  tags:
    - maas-setup
    - rackspace-monitoring-agent-setup
    - rackspace-monitoring-agent-restart
