---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Raxmon client doesn't make it very easy to just get the full check names due
# to limited choices in formatting of output
- name: Enumerate all alarms found
  script: "{{ maas_rpc_dir }}/scripts/rpc-maas-tool.py --tab True --prefix {{ inventory_hostname }} alarms"
  when:
    - inventory_hostname in groups['hosts']
    - expected_checks is defined
  register: maas_after_alarms
  changed_when: False
  failed_when: maas_after_alarms.rc != 0
  tags:
    - maas-install
    - maas-verify

- name: Verify presence of expected alarms
  fail: msg="Expected alarm for check ({{ item }}) not found"
  with_items:
    - "{{ expected_checks.stdout_lines }}"
  when:
    - maas_after_alarms is defined
    - maas_after_alarms.stdout.find("{{ item }}") == -1
  tags:
    - maas-install
    - maas-verify
