---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Stage the git and python artifacts
  hosts: "{{ staging_host | default('localhost') }}"
  user: root
  vars:
    aria_input_file: "/tmp/python_artifact_list.txt"
    rpco_mirror_base_url: "https://rpc-repo.rackspace.com"
    http_proxy_env: "{{ lookup('env', 'http_proxy') | default('not_set', true) }}"
    https_proxy_env: "{{ lookup('env', 'https_proxy') | default('not_set', true) }}"
    https_validate_certs: yes
  tasks:

    - name: Set the staging path
      set_fact:
        staging_path: |-
          {%- if (groups['repo_all'] is defined) and (groups['repo_all'] | length > 0) -%}
          /openstack/{{ hostvars[groups['repo_all'][0]]['inventory_hostname'] }}/repo
          {%- else -%}
          /openstack/stage
          {%- endif -%}
      tags:
        - always

    - name: Fetch the upstream manifest file
      uri:
        url: "{{ rpco_mirror_base_url }}/os-releases/{{ rpc_release }}/MANIFEST.in"
        return_content: yes
        validate_certs: "{{ https_validate_certs | bool }}"
      register: manifest
      tags:
        - always

    # TODO(odyssey4me)
    # Remove this and adjust the fact setting once
    # https://review.openstack.org/433152 is available
    - name: Fetch the upstream venv list
      uri:
        url: "{{ rpco_mirror_base_url }}/venvs/{{ rpc_release }}/ubuntu/"
        return_content: yes
        validate_certs: "{{ https_validate_certs | bool }}"
      register: venv_index
      tags:
        - always

    # TODO(odyssey4me)
    # Remove this and adjust the fact setting once
    # https://review.openstack.org/439659 is available
    - name: Fetch the list of files in the releases folder
      uri:
        url: "{{ rpco_mirror_base_url }}/os-releases/{{ rpc_release }}/"
        return_content: yes
        validate_certs: "{{ https_validate_certs | bool }}"
      register: releases_index
      tags:
        - always

    - name: Derive the lists of artifacts to download
      set_fact:
        #
        # The MANIFEST.in file gives us entries like this for wheels:
        #
        # pools/alembic/alembic-0.8.7-py2.py3-none-any.whl
        # os-releases/r14.0.0rc1/alembic-0.8.7-py2.py3-none-any.whl
        #
        # The first is the pool location, the second is the release
        # folder location. The wheel name is always the same.
        #
        # We only need to download from one accessible location to
        # the pools folder, then implement the symlinks from the
        # releases and links folder as is done in the repo-build
        # process. As such, we filter the list we get based on the
        # 'pools' path. The wheel list is separated from the venv
        # list due to the symlinking that needs to happen later
        # for wheels only.
        #
        # The resulting list has entries such as:
        # pools/alembic/alembic-0.8.7-py2.py3-none-any.whl
        #
        python_wheel_list: |
          {%- set content_list = manifest.content.split('\n') -%}
          {%- set result_list = [] -%}
          {%- for item in content_list -%}
          {%-   if item.split('/')[0] == 'pools' -%}
          {%-     set _ = result_list.append(item) -%}
          {%-   endif -%}
          {%- endfor -%}
          {{- result_list -}}
        #
        # The MANIFEST.in file gives us entries like this for git
        # repositories:
        #
        # openstackgit/nova
        #
        # As we download the git data differently to the wheels,
        # we need to seperate this manifest data from the wheels.
        # As such, we filter the list we get based on the
        # 'openstackgit' path.
        #
        # The resulting list is therefore an unchanged list of
        # only the git folders.
        #
        git_folder_list: |
          {%- set content_list = manifest.content.split('\n') -%}
          {%- set result_list = [] -%}
          {%- for item in content_list -%}
          {%-   if item.split('/')[0] == 'openstackgit' -%}
          {%-     set _ = result_list.append(item) -%}
          {%-   endif -%}
          {%- endfor -%}
          {{- result_list -}}
        #
        # The MANIFEST.in does not currently have the python venvs
        # included in the file. This will be resolved once we are
        # able to complete a python artifact build with the
        # following patch included:
        #   https://review.openstack.org/433152
        #
        # As such we have instead used the repo server's index of
        # files in the folder in order to get the file listing.
        # The data we get is HTML that looks something like this:
        #
        # <html>
        # <head><title>Index of /venvs/r14.0.0rc1/ubuntu/</title></head>
        # <body bgcolor=\"white\">
        # <h1>Index of /venvs/r14.0.0rc1/ubuntu/</h1><hr><pre><a href=\"../\">../</a>
        # <a href=\"aodh-r14.0.0rc1-x86_64.checksum\">aodh-r14.0.0rc1-x86_64.checksum</a>                    27-Feb-2017 17:52                  41
        # <a href=\"aodh-r14.0.0rc1-x86_64.tgz\">aodh-r14.0.0rc1-x86_64.tgz</a>                         27-Feb-2017 17:52            33403695
        #
        # To retrieve the file names we have to split the content
        # into a list by line feeds, then find the link tags and
        # grab just the file name from inside the link tag.
        #
        # The resulting list has entries such as:
        # aodh-r14.0.0rc1-x86_64.checksum
        # aodh-r14.0.0rc1-x86_64.tgz
        #
        python_venv_list: |
          {%- set content_list = venv_index.content.split('\r\n') -%}
          {%- set result_list = [] -%}
          {%- for item in content_list -%}
          {%-   if item | search("<a href.*>.*</a>") -%}
          {%-     set item_clean = item | regex_replace(".*<a href.*>(.*)</a>.*", "\\1") -%}
          {%-     if item_clean != "../" -%}
          {%-       set _ = result_list.append(item_clean) -%}
          {%-     endif -%}
          {%-   endif -%}
          {%- endfor -%}
          {{- result_list -}}
        #
        # The MANIFEST.in does not currently have the non-wheel items
        # from the releases folder included in the file. This will be
        # resolved once we are able to complete a python artifact
        # build with the following patch included:
        #   https://review.openstack.org/439659
        #
        # As such we have instead used the repo server's index of
        # files in the folder in order to get the file listing.
        # The data we get is HTML that looks something like this:
        #
        # <html>
        # <head><title>Index of /os-releases/r14.0.0rc1</title></head>
        # <body bgcolor=\"white\">
        # <h1>Index of /os-releases/r14.0.0rc1</h1><hr><pre><a href=\"../\">../</a>
        # <a href=\"get-pip.py\">get-pip.py</a>                                         27-Feb-2017 17:41             1595408
        # <a href=\"requirements_absolute_requirements.txt\">requirements_absolute_requirements.txt</a>             27-Feb-2017 17:50                6221
        # <a href=\"requirements_constraints.txt\">requirements_constraints.txt</a>                       27-Feb-2017 17:44               13036
        #
        # To retrieve the file names we have to split the content
        # into a list by line feeds, then find the link tags and
        # grab just the file name from inside the link tag. We
        # also need to ignore the wheels in the folder as we already
        # have the wheel listing.
        #
        # The resulting list has entries such as:
        # get-pip.py
        # requirements_absolute_requirements.txt
        # requirements_constraints.txt
        #
        releases_file_list: |
          {%- set content_list = releases_index.content.split('\r\n') -%}
          {%- set result_list = [] -%}
          {%- for item in content_list -%}
          {%-   if item | search("<a href.*>.*</a>") -%}
          {%-     set item_clean = item | regex_replace(".*<a href.*>(.*)</a>.*", "\\1") -%}
          {%-     if item_clean != "../" and (item_clean | search(".txt") or item_clean == "get-pip.py") -%}
          {%-       set _ = result_list.append(item_clean) -%}
          {%-     endif -%}
          {%-   endif -%}
          {%- endfor -%}
          {{- result_list -}}
      tags:
        - always

    - name: Staging folders setup
      file:
        path: "{{ item }}"
        state: "directory"
      with_items:
        - "{{ staging_path }}/links"
        - "{{ staging_path }}/openstackgit"
        - "{{ staging_path }}/os-releases/{{ rpc_release }}"
        - "{{ staging_path }}/venvs/{{ rpc_release }}/ubuntu"
      tags:
        - always

    # The git checkout here is to 'master' to prevent an ansible-lint
    # failure. It will be checked out later to the right SHA in the
    # deployment process.
    - name: Clone git repositories asynchronously
      git:
        repo: "{{ rpco_mirror_base_url }}/{{ item }}"
        dest: "{{ staging_path }}/{{ item }}"
        version: master
        force: yes
      with_items: "{{ git_folder_list }}"
      register: _git_clone
      async: 1800
      poll: 0
      tags:
        - git

    - name: Install aria download manager
      package:
        name: "aria2"
        state: present
      tags:
        - python

    - name: Write python artifact URL list
      copy:
        content: |
          {% for item in python_wheel_list %}
          {{ rpco_mirror_base_url }}/{{ item }}
            dir={{ staging_path }}/{{ item | dirname }}
          {% endfor %}
          {% for item in python_venv_list %}
          {{ rpco_mirror_base_url }}/venvs/{{ rpc_release }}/ubuntu/{{ item }}
            dir={{ staging_path }}/venvs/{{ rpc_release }}/ubuntu
          {% endfor %}
          {% for item in releases_file_list %}
          {{ rpco_mirror_base_url }}/os-releases/{{ rpc_release }}/{{ item }}
            dir={{ staging_path }}/os-releases/{{ rpc_release }}
          {% endfor %}
        dest: "{{ aria_input_file }}"
      tags:
        - python

    - name: Download python artifacts
      command: >-
        aria2c --input-file={{ aria_input_file }}
        --allow-overwrite=true
        --conditional-get=true
        --quiet
        --check-certificate={{ (https_validate_certs | bool) | lower }}
        {{ (http_proxy_env != 'not_set') | ternary('--http-proxy=' ~ http_proxy_env, '') }}
        {{ (https_proxy_env != 'not_set') | ternary('--https-proxy=' ~ https_proxy_env, '') }}
      tags:
        - python

    - name: Python releases symlinks
      file:
        src: "../../{{ item }}"
        dest: "{{ staging_path }}/os-releases/{{ rpc_release }}/{{ item | basename }}"
        state: "link"
      with_items: "{{ python_wheel_list }}"
      tags:
        - python

    - name: Python links symlinks
      file:
        src: "../{{ item }}"
        dest: "{{ staging_path }}/links/{{ item | basename }}"
        state: "link"
      with_items: "{{ python_wheel_list }}"
      tags:
        - python

    - name: Wait for git clones to complete
      async_status:
        jid: "{{ item['ansible_job_id'] }}"
      register: _git_jobs
      until: "{{ _git_jobs['finished'] | bool }}"
      delay: 5
      retries: 360
      with_items: "{{ _git_clone['results'] }}"
      when:
        - item['ansible_job_id'] is defined
      tags:
        - git
