# Elasticsearch versions
# NOTE (alextricity25):
# The elasticsearch version variables needs to be available to the repo_build role
# due to the way it builds out the distro packages dataset. Distro packages within
# a role are indexed using their raw form(jinja is not rendered). The repo_build
# role then attempts to render these datasets, and will fail if it cannot resolve
# a variable. Putting these variables in here ensures the repo_build
# role can interpolate the variables correctly.
elasticsearch_version: 6.3.1
elasticsearch_major_version: 6.x
elasticsearch_reindex_version: 1.7.5

es_instance_name: "openstack"
es_data_dirs: "/var/lib/elasticsearch"
es_log_dir: "/var/log/elasticsearch"
es_scripts: false
es_templates: false
es_version_lock: false
es_heap_size: 1g
es_api_host: "{{ container_address }}"
es_api_port: "{{ elasticsearch_http_port }}"
es_version: "{{ elasticsearch_version }}"
es_major_version: "{{ elasticsearch_major_version }}"
es_basic_auth_username: "admin"
es_basic_auth_password: "{{ elasticsearch_basic_auth_password }}"
es_api_basic_auth_username: "admin"
es_api_basic_auth_password: "{{ elasticsearch_basic_auth_password }}"


es_config:
  node.name: "{{ container_name }}"
  cluster.name: "openstack"
  http.port: "{{ elasticsearch_http_port }}"
  transport.tcp.port: "{{ elasticsearch_tcp_port }}"
  node.data: true
  node.master: true
  network.host: "{{ container_address }}"
  discovery.type: "single-node"

deployment_environment_variables:
  ES_SKIP_SET_KERNEL_PARAMETERS: "true"
