---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Configure the default apt sources for RPC-O
  hosts: "{{ apt_target_group | default('hosts') }}"
  environment: "{{ deployment_environment_variables | default({}) }}"
  user: root
  gather_facts: true
  pre_tasks:
    - name: Ensure local facts directory exists
      file:
        dest: "/etc/ansible/facts.d"
        state: directory
        group: "root"
        owner: "root"
        mode:  "0755"
        recurse: no

    - name: Initialize local facts
      ini_file:
        dest: "/etc/ansible/facts.d/rpc_openstack.fact"
        section: "rpc_artifacts"
        option: initialized
        value: true

    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"
      tags:
        - always

    - name: Set the rpc-openstack variables
      set_fact:
        rpc_openstack: "{{ ansible_local['rpc_openstack']['rpc_artifacts'] }}"

    - name: Set apt_artifact_enabled (based on previous settings)
      set_fact:
        apt_artifact_enabled: "{{ rpc_openstack['apt_artifact_enabled'] }}"
      when:
        - rpc_openstack['apt_artifact_enabled'] is defined
        - apt_artifact_enabled is undefined

    - name: Set apt_artifact_mode (based on previous settings)
      set_fact:
        apt_artifact_mode: "{{ rpc_openstack['apt_artifact_mode'] }}"
      when:
        - rpc_openstack['apt_artifact_mode'] is defined
        - apt_artifact_mode is undefined

    - name: Check for artifacts
      uri:
        url: "{{ rpco_mirror_base_url }}/apt-mirror/integrated/dists/{{ rpc_release }}-{{ ansible_distribution_release }}/Release"
        method: HEAD
      failed_when: false
      register: check_artifacts

    - name: Set apt_artifact_found
      set_fact:
        apt_artifact_found: "{{ check_artifacts.status == 200 }}"

    - name: Set apt_artifact_enabled (based on whether they exist)
      set_fact:
        apt_artifact_enabled: "{{ apt_artifact_found | bool }}"
      when:
        - apt_artifact_enabled is undefined

    - name: Set apt_artifact_mode default value
      set_fact:
        apt_artifact_mode: "strict"
      when:
        - apt_artifact_mode is undefined

    - name: Check if artifacts are enabled but not found
      fail:
        msg: |
          The apt artifacts are enabled but not found. The deployment has
          halted. Please check the artifacts repository is online and available
          before continuing.
      when:
        - apt_artifact_enabled | bool
        - not apt_artifact_found | bool
      tags:
        - always

    - name: Check if artifact mode is set incorrectly
      fail:
        msg: |
          The apt artifact mode is set to the invalid value of '{{ apt_artifact_mode }}'.
          The deployment has halted. Valid values are 'strict' or 'loose'.
      when:
        - apt_artifact_enabled | bool
        - apt_artifact_mode not in ['strict', 'loose']
      tags:
        - always

    - name: Disable other artifacts if apt is disabled
      ini_file:
        dest: "/etc/ansible/facts.d/rpc_openstack.fact"
        section: "rpc_artifacts"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: "py_artifact_enabled", value: false }
      when:
        - not apt_artifact_enabled | bool

  tasks:
    - name: Sync artifact files (all)
      copy:
        src: "{{ item }}"
        dest: "/etc/openstack_deploy/group_vars/all/{{ item | basename }}"
      with_items:
        - files/apt.yml
        - files/lxc.yml
      run_once: true
      delegate_to: localhost
      when:
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Sync artifact files (all)
      copy:
        src: "{{ item }}"
        dest: "/etc/openstack_deploy/{{ item | basename }}"
        mode: "0444"
      with_items:
        - files/user_rpcm_variables.yml
      run_once: true
      delegate_to: localhost
      when:
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Determine the existing Ubuntu repo configuration
      shell: 'sed "s/^[ \t]*//" /etc/apt/sources.list | grep -oP "^deb \K(\[?.*\]?.*ubuntu\S*\/?)(?= {{ ansible_distribution_release }} main)"'
      register: _ubuntu_repo
      changed_when: false
      delegate_to: "{{ physical_host | default(omit) }}"
      when:
        - host_ubuntu_repo is not defined
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Set host_ubuntu_repo fact
      set_fact:
        host_ubuntu_repo: "{{ _ubuntu_repo.stdout_lines[0] }}"
      when:
        - host_ubuntu_repo is not defined
        - _ubuntu_repo.stdout_lines is defined
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Backup the original sources file
      copy:
        src: /etc/apt/sources.list
        dest: /etc/apt/sources.list.original
        remote_src: yes
        force: no

    - name: Replace the apt sources file with our content (artifact 'strict' mode)
      copy:
        content: |
          # Base repository
          deb {{ host_ubuntu_repo }} {{ ansible_distribution_release }} main universe
        dest: "/etc/apt/sources.list"
        backup: yes
      register: apt_sources_configure
      when:
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool
        - apt_artifact_mode == "strict"

    # Set rpco_apt_sources_restore_source to 'local' to have the
    # original apt sources file from the deploy host be pushed out
    # to all hosts and containers.
    - name: Restore the original sources file (artifact 'loose' mode)
      copy:
        src: /etc/apt/sources.list.original
        dest: /etc/apt/sources.list
        remote_src: "{{ rpco_apt_sources_restore_source | default('remote') == 'remote' }}"
        force: yes
      register: apt_sources_restore
      when:
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool
        - apt_artifact_mode != "strict"

    - name: Create the rpco apt sources file
      copy:
        content: |
          # RPC-OpenStack repository
          deb {{ rpco_mirror_base_url }}/apt-mirror/integrated/ {{ rpc_release }}-{{ ansible_distribution_release }} main
        dest: "/etc/apt/sources.list.d/rpco.list"
        backup: yes
      register: apt_sources_configure_rpco
      when:
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Add rpco keys
      apt_key:
        url: "{{ rpco_mirror_base_url }}/apt-mirror/rcbops-release-signing-key.asc"
        state: "present"
      register: add_keys
      until: add_keys | success
      retries: 5
      delay: 2
      when:
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Update apt-cache
      apt:
        update_cache: yes
      when:
        - apt_artifact_enabled | bool
        - apt_artifact_found | bool
        - apt_sources_configure | changed or apt_sources_configure_rpco | changed or apt_sources_restore | changed

  post_tasks:
    - name: Set artifact local fact
      ini_file:
        dest: "/etc/ansible/facts.d/rpc_openstack.fact"
        section: "rpc_artifacts"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - option: "apt_artifact_enabled"
          value: "{{ apt_artifact_enabled }}"
        - option: "apt_artifact_found"
          value: "{{ apt_artifact_found }}"
        - option: "apt_artifact_mode"
          value: "{{ apt_artifact_mode }}"

  vars:
    ansible_python_interpreter: "/usr/bin/python"

  tags:
    - rpc
